Repository OpenMined/PyVertical, pull requests merged in 2020-07, with the labels that each got.

#23 PSI integration
  .github/workflows/scripts/build_psi.sh
  .github/workflows/scripts/lint_python.sh
  .github/workflows/tests.yml
  .gitignore
  README.md
  WORKSPACE
  src/dataloader.py
  src/dataset.py
  src/psi/__init__.py
  src/psi/util.py
  tests/test_dataloader.py
  tests/test_dataset.py
  tests/test_psi.py
Labels: Type: New Feature :heavy_plus_sign:

#37 Fix version of PSI build to old commit
  WORKSPACE
Labels: Status: Completed :heavy_check_mark:, Type: Improvement :chart_with_upwards_trend:

#38 Refactor dataloader
  README.md
  examples/Simple Vertically Partitioned SplitNN.ipynb
  src/dataloader.py
  tests/test_dataloader.py
  tests/test_psi.py
Labels: Status: Completed :heavy_check_mark:, Type: Refactor :hammer:

#41 Sort ids in dataloader
  README.md
  src/dataloader.py
  src/dataset.py
  tests/test_dataset.py
Labels: Status: Completed :heavy_check_mark:, Type: Bug :bug:

#39 PSI functionality into the jupyter notebook example
  .github/workflows/tests.yml
  examples/PyVertical Example.ipynb
  examples/Simple Vertically Partitioned SplitNN.ipynb
Labels: Type: New Feature :heavy_plus_sign:, Type: Refactor :hammer:

#45 Minor readme edits
  README.md
  examples/.gitkeep
Labels: Status: Completed :heavy_check_mark:, Type: Documentation :books:

#52 Change workspace to point to fork
  WORKSPACE
Labels: Status: Completed :heavy_check_mark:, Type: Bug :bug:

#51 Update workspace to latest PSI commit
  WORKSPACE
Labels: Status: Completed :heavy_check_mark:, Type: Bug :bug:
