Repository OpenMined/PyVertical, pull requests merged in 2020-06, with the labels that each got.

#10 Create vertical data splitter
  .gitignore
  README.md
  environment.yml
  examples/.gitkeep
  requirements.txt
  src/__init__.py
  src/data.py
  tests/test_data.py
Labels: Status: Completed :heavy_check_mark:, Type: New Feature :heavy_plus_sign:

#11 Add CI github action
  .github/workflows/scripts/lint_python.sh
  .github/workflows/tests.yml
Labels: Status: Completed :heavy_check_mark:, Type: Testing :test_tube:

#12 Fix requirements.txt
  .flake8
  .github/workflows/scripts/lint_python.sh
  requirements.txt
Labels: Type: Testing :test_tube:

#15 Simulate real data partitions
  src/data.py
  tests/test_data.py
Labels: Status: Completed :heavy_check_mark:, Type: New Feature :heavy_plus_sign:

#19 change partitioning to (images, labels)
  README.md
  src/dataloader.py
  src/dataset.py
  tests/test_dataloader.py
  tests/test_dataset.py
Labels: Status: Completed :heavy_check_mark:, Type: New Feature :heavy_plus_sign:

#21 Simple Vertically partitioned SplitNN
  src/splitnn.py
Labels: Type: New Feature :heavy_plus_sign:
